name: Release2w

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Api_Key: ${{secrets.API_KEY}}
      test:  1234

    steps:
      - name: Publish
        run: |
          pwsh -Command "write-host \"${{$env.test}}\""
