name: Release

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Api_Key: ${{secrets.API_KEY}}


    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          pwsh -Command "Publish-Module -Path "${Env:GITHUB_WORKSPACE}/Output/SeleniumTest2/SeleniumTest2.psd1" -NuGetApiKey ${{secrets.API_KEY}}"