name: Release

on:
  release:
    types: [edited]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Api_Key: ${{secrets.API_KEY}}
      test:  1234

    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          pwsh -Command "write-host 'Hello'"
